# Generated by Django 5.0.1 on 2025-03-03 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopics',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projecttopics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
