# Generated by Django 5.0.1 on 2025-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_projecttopics_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttopics',
            options={'verbose_name_plural': 'プロジェクトのトピック一覧'},
        ),
        migrations.AlterField(
            model_name='projecttopics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
