# Generated by Django 5.0.1 on 2025-03-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_projecttopics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTopics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': '活動のトピック一覧',
                'db_table': 'activity_topics',
            },
        ),
        migrations.CreateModel(
            name='PortfolioTopics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'ポートフォリオのトピック一覧',
                'db_table': 'portfolio_topics',
            },
        ),
        migrations.RenameField(
            model_name='projecttopics',
            old_name='topic_id',
            new_name='id',
        ),
    ]
