# Generated by Django 5.0.1 on 2025-03-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_topicscategory_activitytopics_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopics',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.topicscategory'),
        ),
    ]
