# Generated by Django 5.0.1 on 2025-03-17 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_alter_projecttopics_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('has_creatable_project', models.BooleanField(default=True)),
                ('cnt_project_limit', models.IntegerField(default=1)),
                ('cnt_project', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Util_料金プラン',
                'db_table': 'pricing_plan',
            },
        ),
        migrations.AlterModelOptions(
            name='activitytopics',
            options={'verbose_name_plural': 'ダッシュボード_活動のトピック一覧'},
        ),
        migrations.AlterModelOptions(
            name='portfoliotopics',
            options={'verbose_name_plural': 'ダッシュボード_ポートフォリオのトピック一覧'},
        ),
        migrations.AlterModelOptions(
            name='projecttopics',
            options={'verbose_name_plural': 'ダッシュボード_プロジェクトのトピック一覧'},
        ),
        migrations.CreateModel(
            name='MypageUserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=255)),
                ('member_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.pricingplan')),
            ],
            options={
                'verbose_name_plural': 'マイページ_ユーザープロフィール',
                'db_table': 'mypage_user_profile',
            },
        ),
    ]
