# Generated by Django 5.0.1 on 2025-03-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_pricingplan_alter_activitytopics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypageuserprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
