# Generated by Django 5.0.1 on 2025-03-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_mypageuserprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tips_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Util_Tipsカテゴリ',
                'db_table': 'tips_category',
            },
        ),
        migrations.AlterModelOptions(
            name='topicscategory',
            options={'verbose_name_plural': 'Util_トピックスカテゴリ'},
        ),
        migrations.CreateModel(
            name='TipsContents',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.tipscategory')),
            ],
            options={
                'verbose_name_plural': 'Tips_一覧',
                'db_table': 'tips',
            },
        ),
    ]
