# Generated by Django 5.0.1 on 2025-03-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_tipscategory_alter_topicscategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipscategory',
            name='tips_path',
            field=models.CharField(default='tips', max_length=100, null=True),
        ),
    ]
