# Generated by Django 5.0.1 on 2025-03-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_tipscategory_tips_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypageuserprofile',
            name='account_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mypageuserprofile',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
